<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Surprise!</title>
</head>
<body>
    <h1 style="text-align: center; margin-top: 50px;">Surprise! 🎉</h1>
    <p style="text-align: center; font-size: 20px;">Thanks for visiting!</p>
</body>
</html>
